## 随机生成两个4×4矩阵，求下列指定的四个矩阵，并确定哪些矩阵是相等的

![](../../pic/Pasted%20image%2020260724114145.png)

In [ ]:
import numpy as np

A = np.random.randint(0, 10, size=(4, 4))
B = np.random.randint(0, 10, size=(4, 4))

In [7]:
A1 = A @ B
A2 = B @ A
A3 = (A.T @ B.T).T
A4 = (B.T @ A.T).T
A1,A2, A3, A4

(array([[115, 116, 122, 138],
        [ 82,  88,  78, 138],
        [ 96,  97,  89, 144],
        [100,  86,  98, 112]], dtype=int32),
 array([[ 63, 124, 118,  85],
        [ 62,  95, 108,  75],
        [116, 133, 162, 101],
        [ 96, 108, 140,  84]], dtype=int32),
 array([[ 63, 124, 118,  85],
        [ 62,  95, 108,  75],
        [116, 133, 162, 101],
        [ 96, 108, 140,  84]], dtype=int32),
 array([[115, 116, 122, 138],
        [ 82,  88,  78, 138],
        [ 96,  97,  89, 144],
        [100,  86,  98, 112]], dtype=int32))

Numpy中使用@运算符或者np.dot 进行矩阵的乘法
矩阵间使用 * 运算符 表示按元素相乘